// <auto-generated />
namespace QuanLySieuThi_Version2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class DeleteAllExceptProductAndProductBrand_FixedBugs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeleteAllExceptProductAndProductBrand_FixedBugs));
        
        string IMigrationMetadata.Id
        {
            get { return "201910170957426_DeleteAllExceptProductAndProductBrand_FixedBugs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
