using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace QuanLySieuThi_Version2.GUIs.Manager
{
    public partial class MainForm : DevExpress.XtraEditors.XtraForm
    {
        public MainForm()
        {
            InitializeComponent();

            QuanLySieuThi_Version2.Models.ApplicationDbContext dbContext = new QuanLySieuThi_Version2.Models.ApplicationDbContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Products.Include(path=>path.ProductTypes).Include(path => path.Promotions).Include(path => path.Suppliers).Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.Products.Local.ToBindingList();
        }
        private void tileBar_SelectedItemChanged(object sender, TileItemEventArgs e)
        {
            navigationFrame.SelectedPageIndex = tileBarGroupTables.Items.IndexOf(e.Item);
        }
    }
}